DATA:
  TRAIN_DATASET: 'PanopticL3DStage2'
  Test_DATASET: 'PanopticL3DStage2'

TRAIN:
  BATCH_SIZE: 1
  NUM_WORKERS: 12
  NUM_EPOCHS: 10
  LR: 0.0001
  WEIGHT_DECAY: 0.0001
  LR_DROP: [15]
  LR_BACKBONE: 0.00005
  LR_TEXT_ENCODER: 0.00005

LOSS:
  USE_TARGET_WEIGHT: True
  REG_LOSS: 'l1'
  USE_DIFFERENT_JOINTS_WEIGHT: False
  LOSS_DICE: 5
  LOSS_SIGMOID_FOCAL: 2
  LOSS_CLS: 2
  LOSS_BBOX: 2
  LOSS_GIOU: 2
  LOSS_3D: 1
  LOSS_CORD: 0.1
