DATA:
  TRAIN_DATASET: 'PanopticL3DStage1'
  Test_DATASET: 'PanopticL3DStage1'

TRAIN:
  BATCH_SIZE: 1
  NUM_WORKERS: 12
  NUM_EPOCHS: 20
  LR: 0.0001
  WEIGHT_DECAY: 0.0001
  LR_DROP: [10]

LOSS:
  USE_TARGET_WEIGHT: True
  REG_LOSS: 'l1'
  HEATMAP_WEIGHT: 10000
  BBOX_WEIGHT: 1
  DEPTH_WEIGHT: 1
  USE_DIFFERENT_JOINTS_WEIGHT: False
