RUNNING_MODE: train
SEED: 42
DEVICE: cuda
TRAINING_STAGE: stage1
OUTPUT_PATH: './output'
LOAD_PRETRAINED_MODEL: False
RECORD_OUTPUT_INTERVAL: 10

MODEL:
  VIDEO_BACKBONE:
    EMB_DIM: 256
    NAME: video-swin-t
    USE_CHECKPOINT: False
    CHECKPOINT_FILE: 'swin_tiny_patch244_window877_kinetics400_1k.pth'
  DEPTH_RESNET:
    INPUT_CHANNELS: 9
    NUM_LAYERS: 18
  POSE_RESNET:
    INPUT_CHANNELS: 3
    FINAL_CONV_KERNEL: 1
    DECONV_WITH_BIAS: False
    NUM_DECONV_LAYERS: 3
    NUM_DECONV_FILTERS:
      - 256
      - 256
      - 256
    NUM_DECONV_KERNELS:
      - 4
      - 4
      - 4
    NUM_LAYERS: 152
    PRETRAINED_BACKBONE_FILE: 'pose_resnet_152_384x288.pth.tar'
  TEXT_ENCODER:
    TYPE: 'roberta-base'
    FREEZE_ENCODER: True
  DEFORMTRANSFORMER:
    LEVELS: 4
    EMB_DIM: 256
    NUM_QUERIES: 10
    NUM_CLASSES: 1
    REL_COORD: True
    NHEAD: 8
    ENC_LAYERS: 3
    DEC_LAYERS: 3
    DIM_FEEDFORWARD: 2048
    DROPOUT: 0.1
    NUM_FEATURE_LEVELS: 4
    DEC_N_POINTS: 4
    ENC_N_POINTS: 4
    TWO_STAGE: False
  NUM_BOXES: 10
  BETA: 100.0
  CONTROLLER_LAYERS: 3
  MASK_KERNELS_DIM: 8
  MASK_CHANNELS: 8
  WITH_BOX_REFINE: True
  WINDOW_NUM: 6
  TARGET_TYPE: 'gaussian'

DATA:
  NAME: 'panoptic-L3D'
  NUM_JOINTS: 15
  IMAGE_SIZE:
    - 960
    - 512
  HEATMAP_SIZE:
    - 240
    - 128
  ROOTIDX: 2
  DATA_FORMAT: jpg
  DATA_AUGMENTATION: False
  HEATMAP:
    SYNTHESIZE: True
    NOISE: False
    FIX_CAMERA: True
    SIGMA_SCALE: True
    SIGMA: 3
  ROOT: './data'
  TEST_SUBSET: 'test'
  TRAIN_SUBSET: 'train'
  COLOR_RGB: True
  SCALE_FACTOR: 0
  ROT_FACTOR: 0
  SCALE_FACTOR_RANGE: []
  GROUND_CENTER: False
  RANDOM_PLACE: False
  RANDOM_SPLIT_RATIO: 0.9
  BBOX_EXTENTION: [0.25, 0.12]



ROOT_ESTIMATION:
  SPACE_SIZE:
    - 8000.0
    - 8000.0
    - 2400.0
  SPACE_CENTER:
    - 0.0
    - -500.0
    - 800.0
  INITIAL_CUBE_SIZE:
    - 80
    - 80
    - 24
  MAX_PEOPLE_NUM: 10
  THRESHOLD: 0.3
  PICT_STRUCT:
    GRID_SIZE: [2000.0, 2000.0, 2000.0]
    CUBE_SIZE: [64, 64, 64]
  MATCHED_THRESHOLD_TRAIN: 500
  MATCHED_THRESHOLD_TEST: 20000
  BBOX_EXTENTION: [0.25, 0.12]

TRAIN:
  ENABLE_AMP: False
  CLIP_MAX_NORM: 0.1

VIS:
  SAVE_BATCH_IMAGES_GT: True
  SAVE_BATCH_IMAGES_PRED: True
  SAVE_HEATMAPS_GT: True
  SAVE_HEATMAPS_PRED: True
